### ISSUE TITLE
Timeouts with multi-process Python programs 

### ISSUE THREAD

**Issue by lbeltrame** [rozofs/rozofs#112]
I'm testing rozofs (branch feature/mdevice) using a highly parallelized Python framework (https://github.com/chapmanb/bcbio-nextgen), to evaluate how much it can handle during (extreme) parallel I/O. 

The RozoFS export is made by 4 servers using each 2 250G disks as JBODs, and the servers run quad-core AMD processors, with Bio-Linux 8 (based on Ubuntu 14.0.4 LTS). 

However what is happening is that the Python processes which write on the RozoFS mount point will hang and never return: `strace` shows endless 

```
select(0, NULL, NULL, NULL, {0, 200000}) = 0 (Timeout)
poll([{fd=45, events=POLLIN}], 1, 0)    = 0 (Timeout)
poll([{fd=51, events=POLLIN}], 1, 0)    = 0 (Timeout)
poll([{fd=40, events=POLLIN}], 1, 0)    = 0 (Timeout)
poll([{fd=42, events=POLLIN}], 1, 0)    = 0 (Timeout)
```

This occurs when leveraging the built-in clustering capabilities of IPython. But even using standard multiprocessing, causes the process to hang. 

For the rest, the exports are behaving normally, even under high I/O load, so I'm not sure what is the issue.

**Comment by lbeltrame** [comment]
So far it seems it stems from the use of `subprocess` in the code this program is using. I'll investigate further.

**Comment by rozonicotine** [comment]
Hello,

Thank you for evaluating RozoFS for your application.

In order to help you, could you provide us with the following
information:

*1) export & storage configuration files*
These files are located in the /etc/rozofs/ directory.
For the export (metadata server), this exists only on the
server that provides this fonctionnality. The name of the
file is export.conf.
For the storage nodes, there one configuration file on each
server, and the name is storage.conf.

*2) rozofsmount statitistics:*
From the server from which you run your tests, by entering the
following commands we can get statistics of rozofs:

rozodiag -T mount:0 -c profiler
rozodiag -T mount:0 -c trx

The first command gives statistics about VFS services, and the
second can provide information about some potential time-outs

*3) storcli statistics*
The storcli is the process that handles I/O towards the storage nodes. I am
assuming that we run with the default configuration for which there is only
one storcli associated with rozofsmount.
As rozofsmount, that process can provide statistics about I/O and
transactions:

rozodiag -T mount:0:1 -c profiler
rozodiag -T mount:0:1 -c trx

If there is some transactions time-out, it can be possible to adjust them
according to the network that you are using.

*4) Networking*
Are you using a 1Gb/s or 10 Gb/s network?
Having you enable flow control on your switch and servers?
The support of the pause frame is mandatory, otherwise you can
face some drops at ethernet port level inside the switch. When this situation
occurs, you rely only on TCP timers that have a deep impact on performance
versus the case of the pause frame that acts directly at the MAC layer.


Best Regards,

Didier FERON
CTO

+33.2.51.85.74.21
+33.6.47.93.08.95
didier.feron@rozofs.com <didier.feron@fizians.com>
rozofs.com <http://www.rozofs.com/> - github.com/rozofs

2015-12-14 7:39 GMT+01:00 Luca Beltrame <notifications@github.com>:

> Reopened #112 <https://github.com/rozofs/rozofs/issues/112>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rozofs/rozofs/issues/112#event-490653743>.
>



-- 
Didier FERON
CTO

+33.2.51.85.74.21
+33.6.47.93.08.95
didier.feron@rozofs.com <didier.feron@fizians.com>
rozofs.com <http://www.rozofs.com/> - github.com/rozofs

**Comment by lbeltrame** [comment]
Hello Didier,

we're using a 1Gbit network powered by Cisco switches. I'll let @tony-travis comment on your request with regards to information on the switches as he did their setup. 

The exportfs configuration is available on this gist: https://gist.github.com/lbeltrame/1ec6ae569029590cf625

Storage configuration for each node (called storage.NODENAME.conf to disambiguate) is at this gist: https://gist.github.com/lbeltrame/85ba3147bb527106a05d

I'll run the test in a bit and report the other required information.

**Comment by lbeltrame** [comment]
And these are the other information at the moment of the timeout:

https://gist.github.com/lbeltrame/f8b9a4335c599cb7a76d

**Comment by rozonicotine** [comment]
Hello,

According to the 2 last traces you sent, it appears that there is no
time-out issue.
Now, we saw that there are 2 exports in your configuration. So the issue
might not be on the one for which
you provide us with statistics.

To get the statistics of the other mount point the commands are (assuming
that the instance number of
the second mount point is 1):
rozodiag -T mount:1 -c profiler
rozodiag -T mount:1 -c trx
rozodiag -T mount:1:0 -c profiler
rozodiag -T mount:1:0 -c trx

Best Regards,

Didier


2015-12-14 10:46 GMT+01:00 Luca Beltrame <notifications@github.com>:

> And these are the other information at the moment of the timeout:
>
> https://gist.github.com/lbeltrame/f8b9a4335c599cb7a76d
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rozofs/rozofs/issues/112#issuecomment-164392644>.
>



-- 
Didier FERON
CTO

+33.2.51.85.74.21
+33.6.47.93.08.95
didier.feron@rozofs.com <didier.feron@fizians.com>
rozofs.com <http://www.rozofs.com/> - github.com/rozofs

**Comment by lbeltrame** [comment]
Here are the results:

https://gist.github.com/lbeltrame/9b1782e3e28b68e68e0a

**Comment by rozonicotine** [comment]
Hello,

OK, according to the statistics, that export (filesystem) is not used. I
suggest to return back to some elementary
tests on the first mount point since it looks like that it is the one that
you are using.

I suggest to do a dd test : write a 500 MB file and then read it. But
before running the test, the following statistics
should be cleared:
rozodiag -T mount:0 -c counter reset
rozodiag -T mount:0:1 -c counter reset

Then run a dd write test followed by a read test:
dd if=/dev/zero of=<rozofs_path>/test1 bs=1M count=500
dd if=<rozofs_path>/test1 of=/dev/null bs=1M

Then gets the statistics of rozofsmount and storcli:
rozodiag -T mount:0 -c profiler -c trx
rozodiag -T mount:0:1 -c profiler -c trx

Best Regards,

Didier



2015-12-14 11:29 GMT+01:00 Luca Beltrame <notifications@github.com>:

> Here are the results:
>
> https://gist.github.com/lbeltrame/9b1782e3e28b68e68e0a
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rozofs/rozofs/issues/112#issuecomment-164402791>.
>



-- 
Didier FERON
CTO

+33.2.51.85.74.21
+33.6.47.93.08.95
didier.feron@rozofs.com <didier.feron@fizians.com>
rozofs.com <http://www.rozofs.com/> - github.com/rozofs

**Comment by lbeltrame** [comment]
https://gist.github.com/lbeltrame/02eac6cdeb357416575c

Something perhaps that I didn't make clear is that I observe this when subshells are involved, or multiple processes spawned at the same time. 

The software in question relies heavily on `subprocess` and hence on `fork()` to do its job. Of course it may be a totally unrelated matter.

**Comment by tony-travis** [comment]
On 14/12/15 12:12, Luca Beltrame wrote:
> https://gist.github.com/lbeltrame/02eac6cdeb357416575c
> 
> Something perhaps that I didn't make clear is that I observe this when
> subshells are involved, or multiple processes spawned at the same time.
> 
> The software in question relies heavily on |subprocess| and hence on
> |fork()| to do its job. Of course it may be a totally unrelated matter.

Hi,

I'm away running a Bio-Linux course in Vienna just now and I've only
just seen these emails. The servers in question do have two exports, but
I've now replaced the RozoFS export mounted on /opt so Luca could test
the software using NFS instead. The /data RozoFS mount works OK.

[I won't be able to look at this properly until Thu 17 Dec]

Bye,

  Tony.

-- 
Minke Informatics Limited, Registered in Scotland - Company No. SC419028
Registered Office: 3 Donview, Bridge of Alford, AB33 8QJ, Scotland (UK)
tel. +44(0)19755 63548                    http://minke-informatics.co.uk
mob. +44(0)7985 078324        mailto:tony.travis@minke-informatics.co.uk

**Comment by lbeltrame** [comment]
I've done some more investigation. The same program run from an ext4 partition has no issues of the sort, while it hangs consistently on the RozoFS share. To be precise, more than "hang", the sympthoms are Python or sub-processes not closing after completion.

**Comment by lbeltrame** [comment]
https://files.dennogumi.org/f/46cb3c8186/?raw=1

This is a link to the full strace log from starting the application to the log.

**Comment by lbeltrame** [comment]
I was finally able to make a minimal test case, which involves the use if IPython. The hang occurs when my user has $HOME on the RozoFS mounted export, but not when using a user with $HOME on a local disk.

```python

ipython

Python 2.7.11 |Continuum Analytics, Inc.| (default, Dec  6 2015, 18:08:32) 
Type "copyright", "credits" or "license" for more information.

IPython 4.0.1 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: from joblib import Parallel, delayed
In [2]: from math import sqrt
In [3]: Parallel(n_jobs=8)(delayed(sqrt)(i**2) for i in range(10))
<hang>
```

**Comment by lbeltrame** [comment]
This can also checked by moving the IPython profile directory out of the RozoFS mount point, or conversely, setting it inside the RozoFS mount.

E.g.
```
export IPYTHONDIR=/path/to/rozofs/mounted/export/ipython 
# Now repeating the steps above will hang IPython
export IPYTHONDIR=/path/to/local/disk/ipython
# The steps above will not hang it
````

**Comment by lbeltrame** [comment]
Some more details: this is specifically related to forking, because this does not occur if I make joblib use threads.

I've also excluded the NFS share from the equation, as even a locally-installed Python causes this issue.

**Comment by rozonicotine** [comment]
Hi Luca,

It is not clear for us about the test case that you want to setup. In order
to fix it we need to have a better understanding of
your application and about the test environment.

1) We saw in some traces that there are some parallel jobs
  Do these jobs are run of different servers at the same time or not?
 If it is the case, if your application is distributed who should take care
of the fact that it is distributed file system. So if
 file A is created on server 1 it will be the same on server 2

2) Could you provide us with an example of the test that you are launching?

Best Regards,

Didier

2015-12-21 14:22 GMT+01:00 Luca Beltrame <notifications@github.com>:

> This can also checked by moving the IPython profile directory out of the
> RozoFS mount point, or conversely, setting it inside the RozoFS mount.
>
> E.g.
>
> export IPYTHONDIR=/path/to/rozofs/mounted/export/ipython
> # Now repeating the steps above will hang IPython
> export IPYTHONDIR=/path/to/local/disk/ipython
> # The steps above will not hang it
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rozofs/rozofs/issues/112#issuecomment-166304633>.
>



-- 
Didier FERON
CTO

+33.2.51.85.74.21
+33.6.47.93.08.95
didier.feron@rozofs.com <didier.feron@fizians.com>
rozofs.com <http://www.rozofs.com/> - github.com/rozofs

**Comment by lbeltrame** [comment]
Hello,

The jobs run all at the same time. In this case they run locally on the same server, but they can also run distributed. I've removed the distributed part to ensure it wasn't a problem of the SLURM scheduler coupled with the IPython clusters.

So all the recent tests you've seen were made locally on a single server.

See the minimal test cases I posted earlier using IPython and joblib. I can reliably cause hangs 100% of the cases.

**Comment by lbeltrame** [comment]
To clarify in case I wasn't too clear: the application I'm trying to use is way more complex than this one, but I was able to reduce the cause of the hang to this simple program so perhaps it could be used to reproduce / investigate further.

**Comment by rozonicotine** [comment]
Hi Luca,

We got it.
It is an issue related to use of the lock where we forget to update a
resource. After a while (32 lock release), the system was
entering by error in a buffer depletion state, and so none of the VFS
commands sent to RozoFS were processed.

We will do the fix, and inform you when it is ready. Thank you for
narrowing that issue with a simple python test case.

Best Regards,

Didier

2015-12-21 14:55 GMT+01:00 Luca Beltrame <notifications@github.com>:

> To clarify in case I wasn't too clear: the application I'm trying to use
> is way more complex than this one, but I was able to reduce the cause of
> the hang to this simple program so perhaps it could be used to reproduce /
> investigate further.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rozofs/rozofs/issues/112#issuecomment-166310601>.
>



-- 
Didier FERON
CTO

+33.2.51.85.74.21
+33.6.47.93.08.95
didier.feron@rozofs.com <didier.feron@fizians.com>
rozofs.com <http://www.rozofs.com/> - github.com/rozofs

**Comment by lbeltrame** [comment]
Thanks a lot for identifying the issue!

**Comment by rozonicotine** [comment]
Hi Luca,

the fix is available under github ( feature/mdevice branch):

storlci buffer depletion:

fix an issue when a lock() is released while there is pending data.

You can either synchronize your client with git pull origin
feature/mdevice or download the

last available packages (alpha85).

Best Regards,

Didier


2015-12-21 17:29 GMT+01:00 Luca Beltrame <notifications@github.com>:

> Thanks a lot for identifying the issue!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rozofs/rozofs/issues/112#issuecomment-166351197>.
>



-- 
Didier FERON
CTO

+33.2.51.85.74.21
+33.6.47.93.08.95
didier.feron@rozofs.com <didier.feron@fizians.com>
rozofs.com <http://www.rozofs.com/> - github.com/rozofs

**Comment by lbeltrame** [comment]
I updated the packages to alpha85 and redid the exports (moved the export directories away and re-started exportd). However the hang is still present using the minimal test case.

**Comment by lbeltrame** [comment]
Also, Python zombie process stay around forever until the machine is rebooted.

**Comment by rozodopamine** [comment]
The test works for me in apha85 ! Can you point me something I may not do
rigth ? By the way can you send me the output of the following command
rozodiag -T mount:0 -T mount:0:1 -T mount:0:2 -c all.
Regards,
JPierre

rozodiag -T mount:0 -c git
____[rozofsmount 0]__[git ]____
git : 2.0.~alpha85 LEGACY Debian GNU/Linux 7 (wheezy) 2015/12/24 10H25 HEAD
2f31768d3f00dbffa9d666029aef59bf38f3eb93
root@debian:/home/jean-pierre/rozoClients/r2xoff/tests# cd
/home/jean-pierre/rozoClients/r2xoff/tests/SIMU/mnt0_eid1_site0
root@debian:/home/jean-pierre/rozoClients/r2xoff/tests/SIMU/mnt0_eid1_site0#
echo $IPYTHONDIR
/home/jean-pierre/rozoClients/r2xoff/tests/SIMU/mnt0_eid1_site0
root@debian:/home/jean-pierre/rozoClients/r2xoff/tests/SIMU/mnt0_eid1_site0#
ipython
Python 2.7.3 (default, Mar 13 2014, 11:03:55)
Type "copyright", "credits" or "license" for more information.

IPython 4.0.1 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]:  from joblib import Parallel, delayed

In [2]: from math import sqrt

In [3]: Parallel(n_jobs=8)(delayed(sqrt)(i**2) for i in range(10))
Out[3]: [0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0]

In [4]: Parallel(n_jobs=10)(delayed(sqrt)(i**2) for i in range(10))
Out[4]: [0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0]

In [5]: Parallel(n_jobs=16)(delayed(sqrt)(i**2) for i in range(10))
Out[5]: [0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0]

In [6]: exit
root@debian:/home/jean-pierre/rozoClients/r2xoff/tests/SIMU/mnt0_eid1_site0#
ls
extensions  nbextensions  profile_default

2015-12-23 17:36 GMT+01:00 Luca Beltrame <notifications@github.com>:

> Also, Python zombie process stay around forever until the machine is
> rebooted.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rozofs/rozofs/issues/112#issuecomment-166938486>.
>



-- 
Jean-Pierre Monchanin - Customer support


*jean-pierre.monchanin@rozofs.com
<jean-pierre.monchanin@rozofs.com>www.rozofs.com
<http://www.rozofs.com>https://github.com/rozofs/rozofs
<https://github.com/rozofs/rozofs>*

**Comment by lbeltrame** [comment]
In data gioved� 24 dicembre 2015 01:35:41 CET, rozodopamine ha scritto:

Hello,

> The test works for me in apha85 ! Can you point me something I may not do
> rigth ? By the way can you send me the output of the following command
> rozodiag -T mount:0 -T mount:0:1 -T mount:0:2 -c all.

Just for reference the versions I have built:

$ apt search rozo
Sorting... Done
Full Text Search... Done
nagios-plugins-rozofs/now 2.0.~alpha85-1~trusty0+1 all [installed,local]
  RozoFS filesystem (Nagios plugins)

rozofs-dbg/now 2.0.~alpha85-1~trusty0+1 amd64 [installed,local]
  RozoFS filesystem (debugging symbols)

rozofs-exportd/now 2.0.~alpha85-1~trusty0+1 amd64 [installed,local]
  RozoFS filesystem (export daemon)

rozofs-geomgr/now 2.0.~alpha85-1~trusty0+1 amd64 [installed,local]
  RozoFS filesystem (geo-replication software)

rozofs-manager-agent/now 2.0.~alpha85-1~trusty0+1 amd64 [installed,local]
  RozoFS filesystem (management daemon)

rozofs-manager-cli/now 2.0.~alpha85-1~trusty0+1 amd64 [installed,local]
  RozoFS filesystem (management cli)

rozofs-manager-lib/now 2.0.~alpha85-1~trusty0+1 amd64 [installed,local]
  RozoFS filesystem (management library)

rozofs-rozodiag/now 2.0.~alpha85-1~trusty0+1 amd64 [installed,local]
  RozoFS filesystem (diagnostic tools)

rozofs-rozofsmount/now 2.0.~alpha85-1~trusty0+1 amd64 [installed,local]
  RozoFS filesystem (mount utility)

rozofs-rozolauncher/now 2.0.~alpha85-1~trusty0+1 amd64 [installed,local]
  RozoFS filesystem (daemon launcher)

rozofs-storaged/now 2.0.~alpha85-1~trusty0+1 amd64 [installed,local]
  RozoFS filesystem (storage daemon)

All the 4 nodes have the same configuration (no version mismatch). I also have 
rebooted them (minus the export host) to ensure that they started off in a 
clean state.

Statistics on one host: https://gist.github.com/lbeltrame/257d5e4d97865eac0188

**Comment by rozodopamine** [comment]
The test works for me in apha85 ! Can you point me something I may not do
rigth ? By the way can you send me the output of the following command
rozodiag -T mount:0 -T mount:0:1 -T mount:0:2 -c all.
Regards,
JPierre

rozodiag -T mount:0 -c git
____[rozofsmount 0]__[git ]____
git : 2.0.~alpha85 LEGACY Debian GNU/Linux 7 (wheezy) 2015/12/24 10H25 HEAD
2f31768d3f00dbffa9d666029aef59bf38f3eb93
root@debian:/home/jean-pierre/rozoClients/r2xoff/tests# cd
/home/jean-pierre/rozoClients/r2xoff/tests/SIMU/mnt0_eid1_site0
root@debian:/home/jean-pierre/rozoClients/r2xoff/tests/SIMU/mnt0_eid1_site0#
echo $IPYTHONDIR
/home/jean-pierre/rozoClients/r2xoff/tests/SIMU/mnt0_eid1_site0
root@debian:/home/jean-pierre/rozoClients/r2xoff/tests/SIMU/mnt0_eid1_site0#
ipython
Python 2.7.3 (default, Mar 13 2014, 11:03:55)
Type "copyright", "credits" or "license" for more information.

IPython 4.0.1 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]:  from joblib import Parallel, delayed

In [2]: from math import sqrt

In [3]: Parallel(n_jobs=8)(delayed(sqrt)(i**2) for i in range(10))
Out[3]: [0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0]

In [4]: Parallel(n_jobs=10)(delayed(sqrt)(i**2) for i in range(10))
Out[4]: [0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0]

In [5]: Parallel(n_jobs=16)(delayed(sqrt)(i**2) for i in range(10))
Out[5]: [0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0]

In [6]: exit
root@debian:/home/jean-pierre/rozoClients/r2xoff/tests/SIMU/mnt0_eid1_site0#
ls
extensions  nbextensions  profile_default


2015-12-21 14:10 GMT+01:00 Luca Beltrame <notifications@github.com>:

> I was finally able to make a minimal test case, which involves the use if
> IPython. The hang occurs when my user has $HOME on the RozoFS mounted
> export, but not when using a user with $HOME on a local disk.
>
> ipython
>
> Python 2.7.11 |Continuum Analytics, Inc.| (default, Dec  6 2015, 18:08:32)
> Type "copyright", "credits" or "license" for more information.
>
> IPython 4.0.1 -- An enhanced Interactive Python.
> ?         -> Introduction and overview of IPython's features.%quickref -> Quick reference.help      -> Python's own help system.object?   -> Details about 'object', use 'object??' for extra details.
>
> In [1]: from joblib import Parallel, delayed
> In [2]: from math import sqrt
> In [3]: Parallel(n_jobs=8)(delayed(sqrt)(i**2) for i in range(10))<hang>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rozofs/rozofs/issues/112#issuecomment-166302028>.
>



-- 
Jean-Pierre Monchanin - Customer support


*jean-pierre.monchanin@rozofs.com
<jean-pierre.monchanin@rozofs.com>www.rozofs.com
<http://www.rozofs.com>https://github.com/rozofs/rozofs
<https://github.com/rozofs/rozofs>*

**Comment by lbeltrame** [comment]
In data giovedì 24 dicembre 2015 02:41:37 CET, rozodopamine ha scritto:

> rigth ? By the way can you send me the output of the following command
> rozodiag -T mount:0 -T mount:0:1 -T mount:0:2 -c all.

Is the link I provided in the past answer accessible?

I don't have a mount:0:2, that generates a connection refused errors. For 
storage configuration I'm using , refer to the original report (all files have 
been provided).

I've tested both exports and they both hang. An additional test I could try 
would be to make a new fresh volume from scratch (separate from the others) 
and test it again. 

I'll let you know ASAP: as I'm on holiday, I may get around to it early next 
year (2-4th Jan).

**Comment by rozoadrenaline** [comment]
According to your start config for [rozofsmount 0](https://gist.github.com/lbeltrame/257d5e4d97865eac0188#file-gistfile1-txt-L487) and [1](https://gist.github.com/lbeltrame/257d5e4d97865eac0188#file-gistfile1-txt-L1569) you didn't enable the posix file feature while it's seems to be necessary  for your usecase.

For enable lock feature see `man 8 rozofsmount`:

```
-o posixlock
              Active support for POSIX file lock.

-o bsdlock
              Active support for BSD file lock.

```
Bye.

Sylvain

**Comment by lbeltrame** [comment]
Indeed, it works now! I'll add `posixlock` to the mount options. Thanks a lot!
